---
- name: Install common software
  apt: name={{item}} state=latest update-cache=yes cache_valid_time=864000
  with_items:
    - htop
    - strace
    - make
    - gcc
    - lsof
    - vim
    - curl
    - git
    - sysstat
    - iotop
    - dstat
    - iptraf
    - screen
    - wget
    - python-pip
    - python-dev
    - atop
    - fail2ban
